app:
  image: nvmobdev
  ports:
    - "80:3000"
    - "81:4000"
  links:
    - mongo
  environment:
    - ROOT_URL=http://localhost
    - MONGO_URL=mongodb://mongo:27017/meteor

mongo:
  image: mongo:latest 